#pragma once

//TODO: check for gaps in code, map params

typedef void(*GetFaceFlags_t)();
typedef void(*PingPong_t)();
typedef void(*TempTransform_t)();
typedef void(*GetBoardInfoPointer2_t)();
typedef void(*GetBoardStats_t)();
typedef void(*GetStat_t)();
typedef void(*TempRestore_t)();
typedef void(*Trick_PlayerInit_t)();
typedef void(*Trick_TakeOff_t)();
typedef void(*Trick_Trick_t)();
typedef void(*Trick_HoldTrick_t)();
typedef void(*EndManual_t)();
typedef void(*AddTrickItem_t)();
typedef void(*Get180s_t)();
typedef void(*Trick_Land_t)();
typedef void(*Trick_Bail_t)();
typedef void(*TranslatedPartNumber_t)();
typedef void(*ShiftBoard_t)();
typedef void(*Fatten_t)();
typedef void(*Vibrate_t)();
typedef void(*StateTransition_t)();
typedef void(*MaybeFlipAnimationTransition_t)();
typedef void(*Debug_RunAnim_t)();
typedef void(*Debug_RunAnim1_t)();
typedef void(*Debug_RunAnim2_t)();
typedef void(*Debug_RunAnim3_t)();
typedef void(*Panel_TakeOff_t)();
typedef void(*Bail_t)();
typedef void(*ProjectCVectorToPlane_t)();
typedef void(*CVectorRotateToPlane_t)();
typedef void(*UberFrig_t)();
typedef void(*TrickObRailNode_t)();
typedef void(*CheckForLipGaps_t)();
typedef void(*FUN_0048e720_t)();
typedef void(*StartGrind_t)();
typedef void(*HandleStickToRail_t)();
typedef void(*HandleBailOnLanding_t)();
typedef void(*HandleBailPerpendicular_t)();
typedef void(*TriggerTrick_t)();
typedef void(*TriggerTrick2_t)();
typedef void(*ButtonRecord_t)();
typedef void(*FUN_0048f690_t)();
typedef void(*FUN_0048f740_t)();
typedef void(*FUN_0048f830_t)();
typedef void(*ButtonRemoveLast_t)();
typedef void(*GetDirection_t)();
typedef void(*UpdateButtons_t)();
typedef void(*QueueTrick_t)();
typedef void(*UpdateQueue_t)();
typedef void(*ActionButtonHeld_t)();
typedef void(*GetPreviousPressedEvent_t)();
typedef void(*MaybeTriggerTrick_t)();
typedef void(*EnsureGTricksLoaded_t)();
typedef void(*UnloadGTricks_t)();
typedef void(*ExtraAnims_Reset_t)();
typedef void(*ExtraAnims_Add_t)();
typedef void(*ExtraAnims_There_t)();
typedef void(*ExtraAnims_AddTrick_t)();
typedef void(*ExtraAnims_AddTrickTable_t)();
typedef void(*ExtraAnims_AddSkatersAnims_t)();
typedef void(*HandleTricksNew_t)();
typedef void(*InterpolateFrame_t)();
typedef void(*CalcAnimLeanFrame_t)();
typedef void(*HandleSpin_t)();
typedef void(*AlignHeadingOnRail_t)();
typedef void(*CreateRailSparks_t)();
typedef void(*TweakRailScore_t)();
typedef void(*HandleGrindOffSound_t)();
typedef void(*LeaveRail_t)();
typedef void(*DoOnRailPhysics_t)();
typedef void(*SkateOffGround_t)();
typedef void(*CheckSide_t)();
typedef void(*DoTerrainEffects_t)();
typedef void(*DoManualPhysics_t)();
typedef void(*MoveOriginTo_t)();
typedef void(*HandleTruckSqueakSound_t)();
typedef void(*CheckForTransfer_t)();
typedef void(*CancelLastTrick_t)();
typedef void(*Handle_AutoTurn_t)();
typedef void(*DoOnGroundPhysics_t)();
typedef void(*HandleLeaningBail_t)();
typedef void(*HitAirPoly_t)();
typedef void(*MaybeManual_t)();
typedef void(*DriftUpright_t)();
typedef void(*DoInAirPhysics_t)();
typedef void(*DoFootPlantPhysics_t)();
typedef void(*DoHandplantPhysics_t)();
typedef void(*DoWallridePhysics_t)();
typedef void(*Ollie_Sound_t)();
typedef void(*Land_Sound_t)();
typedef void(*HandleJump_t)();
typedef void(*HandleKick_t)();
typedef void(*RotateHeadingAndVelocity_t)();
typedef void(*ReflectHeadingVelocityInPlane_t)();
typedef void(*AlignToFallLine_t)();
typedef void(*UprightSideways_t)();
typedef void(*FRUVectorsFromRotMatrix_t)();
typedef void(*RotMatrixFromFRUVectors_t)();
typedef void(*SetAnglesFromHeading_t)();
typedef void(*HandleContinuousSounds_t)();
typedef void(*OrientToNormal_t)();
typedef void(*HandlePlayersCollisions_t)();
typedef void(*LimitFinalSpeed_t)();
typedef void(*CheckForTriggers_t)();
typedef void(*HandleBailStates_t)();
typedef void(*CheckSideCollisions_t)();
typedef void(*MaybeCess_t)();
typedef void(*HandlePhysicsStates_t)();
typedef void(*HandleBraking_t)();
typedef void(*HandleFlips_t)();
typedef void(*HandleTimer_t)();
typedef void(*HandleNollie_t)();
typedef void(*DoPhysics_t)();

static const GetFaceFlags_t GetFaceFlags = (GetFaceFlags_t)0x48c370;
static const PingPong_t PingPong = (PingPong_t)0x48c460;
static const TempTransform_t TempTransform = (TempTransform_t)0x48c4f0;
static const GetBoardInfoPointer2_t GetBoardInfoPointer2 = (GetBoardInfoPointer2_t)0x48c980;
static const GetBoardStats_t GetBoardStats = (GetBoardStats_t)0x48cac0;
static const GetStat_t GetStat = (GetStat_t)0x48cc90;
static const TempRestore_t TempRestore = (TempRestore_t)0x48ce80;
static const Trick_PlayerInit_t Trick_PlayerInit = (Trick_PlayerInit_t)0x48cec0;
static const Trick_TakeOff_t Trick_TakeOff = (Trick_TakeOff_t)0x48cee0;
static const Trick_Trick_t Trick_Trick = (Trick_Trick_t)0x48cf80;
static const Trick_HoldTrick_t Trick_HoldTrick = (Trick_HoldTrick_t)0x48d010;
static const EndManual_t EndManual = (EndManual_t)0x48d0b0;
static const AddTrickItem_t AddTrickItem = (AddTrickItem_t)0x48d0f0;
static const Get180s_t Get180s = (Get180s_t)0x48d190;
static const Trick_Land_t Trick_Land = (Trick_Land_t)0x48d1e0;
static const Trick_Bail_t Trick_Bail = (Trick_Bail_t)0x48d410;
static const TranslatedPartNumber_t TranslatedPartNumber = (TranslatedPartNumber_t)0x48d4d0;
static const ShiftBoard_t ShiftBoard = (ShiftBoard_t)0x48d580;
static const Fatten_t Fatten = (Fatten_t)0x48d650;
static const Vibrate_t Vibrate = (Vibrate_t)0x48d8b0;
static const StateTransition_t StateTransition = (StateTransition_t)0x48d9a0;
static const MaybeFlipAnimationTransition_t MaybeFlipAnimationTransition = (MaybeFlipAnimationTransition_t)0x48dbd0;
static const Debug_RunAnim_t Debug_RunAnim = (Debug_RunAnim_t)0x48dce0;
static const Debug_RunAnim1_t Debug_RunAnim1 = (Debug_RunAnim1_t)0x48dd10;
static const Debug_RunAnim2_t Debug_RunAnim2 = (Debug_RunAnim2_t)0x48dd40;
static const Debug_RunAnim3_t Debug_RunAnim3 = (Debug_RunAnim3_t)0x48dd70;
static const Panel_TakeOff_t Panel_TakeOff = (Panel_TakeOff_t)0x48ddb0;
static const Bail_t Bail = (Bail_t)0x48ddc0;
static const ProjectCVectorToPlane_t ProjectCVectorToPlane = (ProjectCVectorToPlane_t)0x48df00;
static const CVectorRotateToPlane_t CVectorRotateToPlane = (CVectorRotateToPlane_t)0x48df70;
static const UberFrig_t UberFrig = (UberFrig_t)0x48e020;
static const TrickObRailNode_t TrickObRailNode = (TrickObRailNode_t)0x48e3d0;
static const CheckForLipGaps_t CheckForLipGaps = (CheckForLipGaps_t)0x48e560;
static const FUN_0048e720_t FUN_0048e720 = (FUN_0048e720_t)0x48e720;
static const StartGrind_t StartGrind = (StartGrind_t)0x48e7e0;
static const HandleStickToRail_t HandleStickToRail = (HandleStickToRail_t)0x48edc0;
static const HandleBailOnLanding_t HandleBailOnLanding = (HandleBailOnLanding_t)0x48efc0;
static const HandleBailPerpendicular_t HandleBailPerpendicular = (HandleBailPerpendicular_t)0x48f070;
static const TriggerTrick_t TriggerTrick = (TriggerTrick_t)0x48f470;
static const TriggerTrick2_t TriggerTrick2 = (TriggerTrick2_t)0x48f500;
static const ButtonRecord_t ButtonRecord = (ButtonRecord_t)0x48f580;
static const FUN_0048f690_t FUN_0048f690 = (FUN_0048f690_t)0x48f690;
static const FUN_0048f740_t FUN_0048f740 = (FUN_0048f740_t)0x48f740;
static const FUN_0048f830_t FUN_0048f830 = (FUN_0048f830_t)0x48f830;
static const ButtonRemoveLast_t ButtonRemoveLast = (ButtonRemoveLast_t)0x48f920;
static const GetDirection_t GetDirection = (GetDirection_t)0x48fa10;
static const UpdateButtons_t UpdateButtons = (UpdateButtons_t)0x48fa80;
static const QueueTrick_t QueueTrick = (QueueTrick_t)0x48fb80;
static const UpdateQueue_t UpdateQueue = (UpdateQueue_t)0x48fcf0;
static const ActionButtonHeld_t ActionButtonHeld = (ActionButtonHeld_t)0x48fde0;
static const GetPreviousPressedEvent_t GetPreviousPressedEvent = (GetPreviousPressedEvent_t)0x48fe50;
static const MaybeTriggerTrick_t MaybeTriggerTrick = (MaybeTriggerTrick_t)0x48fed0;
static const EnsureGTricksLoaded_t EnsureGTricksLoaded = (EnsureGTricksLoaded_t)0x490380;
static const UnloadGTricks_t UnloadGTricks = (UnloadGTricks_t)0x490410;
static const ExtraAnims_Reset_t ExtraAnims_Reset = (ExtraAnims_Reset_t)0x490450;
static const ExtraAnims_Add_t ExtraAnims_Add = (ExtraAnims_Add_t)0x490490;
static const ExtraAnims_There_t ExtraAnims_There = (ExtraAnims_There_t)0x490560;
static const ExtraAnims_AddTrick_t ExtraAnims_AddTrick = (ExtraAnims_AddTrick_t)0x490600;
static const ExtraAnims_AddTrickTable_t ExtraAnims_AddTrickTable = (ExtraAnims_AddTrickTable_t)0x490640;
static const ExtraAnims_AddSkatersAnims_t ExtraAnims_AddSkatersAnims = (ExtraAnims_AddSkatersAnims_t)0x4906d0;
static const HandleTricksNew_t HandleTricksNew = (HandleTricksNew_t)0x490790;
static const InterpolateFrame_t InterpolateFrame = (InterpolateFrame_t)0x4907c0;
static const CalcAnimLeanFrame_t CalcAnimLeanFrame = (CalcAnimLeanFrame_t)0x490810;
static const HandleSpin_t HandleSpin = (HandleSpin_t)0x490c60;
static const AlignHeadingOnRail_t AlignHeadingOnRail = (AlignHeadingOnRail_t)0x491700;
static const CreateRailSparks_t CreateRailSparks = (CreateRailSparks_t)0x491830;
static const TweakRailScore_t TweakRailScore = (TweakRailScore_t)0x491910;
static const HandleGrindOffSound_t HandleGrindOffSound = (HandleGrindOffSound_t)0x491980;
static const LeaveRail_t LeaveRail = (LeaveRail_t)0x491a70;
static const DoOnRailPhysics_t DoOnRailPhysics = (DoOnRailPhysics_t)0x491b00;
static const SkateOffGround_t SkateOffGround = (SkateOffGround_t)0x492fe0;
static const CheckSide_t CheckSide = (CheckSide_t)0x4930b0;
static const DoTerrainEffects_t DoTerrainEffects = (DoTerrainEffects_t)0x4933e0;
static const DoManualPhysics_t DoManualPhysics = (DoManualPhysics_t)0x4935b0;
static const MoveOriginTo_t MoveOriginTo = (MoveOriginTo_t)0x493950;
static const HandleTruckSqueakSound_t HandleTruckSqueakSound = (HandleTruckSqueakSound_t)0x493b70;
static const CheckForTransfer_t CheckForTransfer = (CheckForTransfer_t)0x493be0;
static const CancelLastTrick_t CancelLastTrick = (CancelLastTrick_t)0x493bf0;
static const Handle_AutoTurn_t Handle_AutoTurn = (Handle_AutoTurn_t)0x493c50;
static const DoOnGroundPhysics_t DoOnGroundPhysics = (DoOnGroundPhysics_t)0x493e40;
static const HandleLeaningBail_t HandleLeaningBail = (HandleLeaningBail_t)0x495250;
static const HitAirPoly_t HitAirPoly = (HitAirPoly_t)0x495390;
static const MaybeManual_t MaybeManual = (MaybeManual_t)0x4954a0;
static const DriftUpright_t DriftUpright = (DriftUpright_t)0x4956e0;
static const DoInAirPhysics_t DoInAirPhysics = (DoInAirPhysics_t)0x495830;
static const DoFootPlantPhysics_t DoFootPlantPhysics = (DoFootPlantPhysics_t)0x496ce0;
static const DoHandplantPhysics_t DoHandplantPhysics = (DoHandplantPhysics_t)0x496ec0;
static const DoWallridePhysics_t DoWallridePhysics = (DoWallridePhysics_t)0x497000;
static const Ollie_Sound_t Ollie_Sound = (Ollie_Sound_t)0x497aa0;
static const Land_Sound_t Land_Sound = (Land_Sound_t)0x497ad0;
static const HandleJump_t HandleJump = (HandleJump_t)0x497b70;
static const HandleKick_t HandleKick = (HandleKick_t)0x498900;
static const RotateHeadingAndVelocity_t RotateHeadingAndVelocity = (RotateHeadingAndVelocity_t)0x498df0;
static const ReflectHeadingVelocityInPlane_t ReflectHeadingVelocityInPlane = (ReflectHeadingVelocityInPlane_t)0x4993c0;
static const AlignToFallLine_t AlignToFallLine = (AlignToFallLine_t)0x499950;
static const UprightSideways_t UprightSideways = (UprightSideways_t)0x499c20;
static const FRUVectorsFromRotMatrix_t FRUVectorsFromRotMatrix = (FRUVectorsFromRotMatrix_t)0x49a0c0;
static const RotMatrixFromFRUVectors_t RotMatrixFromFRUVectors = (RotMatrixFromFRUVectors_t)0x49a140;
static const SetAnglesFromHeading_t SetAnglesFromHeading = (SetAnglesFromHeading_t)0x49a1c0;
static const HandleContinuousSounds_t HandleContinuousSounds = (HandleContinuousSounds_t)0x49a260;
static const OrientToNormal_t OrientToNormal = (OrientToNormal_t)0x49a970;
static const HandlePlayersCollisions_t HandlePlayersCollisions = (HandlePlayersCollisions_t)0x49abe0;
static const LimitFinalSpeed_t LimitFinalSpeed = (LimitFinalSpeed_t)0x49ad70;
static const CheckForTriggers_t CheckForTriggers = (CheckForTriggers_t)0x49b020;
static const HandleBailStates_t HandleBailStates = (HandleBailStates_t)0x49b180;
static const CheckSideCollisions_t CheckSideCollisions = (CheckSideCollisions_t)0x49b2a0;
static const MaybeCess_t MaybeCess = (MaybeCess_t)0x49b3b0;
static const HandlePhysicsStates_t HandlePhysicsStates = (HandlePhysicsStates_t)0x49b460;
static const HandleBraking_t HandleBraking = (HandleBraking_t)0x49b7e0;
static const HandleFlips_t HandleFlips = (HandleFlips_t)0x49bd10;
static const HandleTimer_t HandleTimer = (HandleTimer_t)0x49bd60;
static const HandleNollie_t HandleNollie = (HandleNollie_t)0x49be50;
static const DoPhysics_t DoPhysics = (DoPhysics_t)0x49bf60;
